# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc5edd630023452075b91e4e65abd5e01d6d58bbc6b6db5f2629c61800aeb4da515408ea441abd8a9859f9ad21ce82da9ad17a8ed44ca1fb5387757f1e4dffac

test:
  secret_key_base: 18787ad6d1bbf15fec95c7392de685c85bda72842320f10d771108dac09b26f3c0672748a7e52e95b3b6d0c928386381dc8190119ae3532df64e0b2602a5daa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
